config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'homes#top'
  resource :user, only: [:new, :create, :show]
  
  resource :calendar, only: [:show]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  
  resources 'attendances'


  # Defines the root path route ("/") logout_path
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  ## 勤務中かどうか
  def is_working?
    !start_time.nil? && !is_rest? && !is_finished_work?
  end

  ## 休憩中かどうか
  def is_rest?
    !rest_start_time.nil? && rest_end_time.nil?
  end

  def is_finished_rest?
    !rest_end_time.nil?
  end

  ## その日を退勤しているかどうか
  def is_finished_work?
    !end_time.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ## helperメソッドとしてViewで使えるようにする
helper_method :current_user

  def login
    ## ログインがされているかどうか確認
    if current_user.nil?
      redirect_to login_path, alert: "You have to log in."
    end
  end

  def already 
    ## 現在のユーザーがnilか確認。unlessはifの逆の意味
    unless current_user.nil?
      redirect_to new_attendance_path, notice: "You are already logged in."
    end
  end

  def current_user
    if session[:user_id]
      current_user ||= User.find(session[:user_id])
    end
  end
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new 
    user_id = current_user.id
    @user = User.where(id: user_id).first
    attendances = Attendance.where(user_id: user_id)  
    @attendance = attendances.last
  end

  def index 
  end


   def create
    attendance = Attendance.new
    attendance.start_time = Time.now
    attendance.user_id = current_user.id
    @attendance = attendance
    if attendance.save
      redirect_to new_attendance_path, notice: "出社しました"
      @attendance = attendance
    end
  end

def update

   time_type = params[:type]
   attendance = Attendance.find(params[:id])
  
   @attendance = attendance
   ## 退勤
   if time_type == "end"
    if @attendance.update(end_time: Time.now)
      redirect_to new_attendance_path, notice: "退勤しました"
    end
   end

   ##休憩時間開始
   if time_type == "rest_start"
      if @attendance.update(rest_start_time: Time.now)
        redirect_to new_attendance_path, notice: "休憩入りました"
    end
  end

   ##休憩時間終了
   if time_type == "rest_end"
      if @attendance.update(rest_end_time: Time.now)
        redirect_to new_attendance_path, notice: "休憩から戻りました"
    end
  end

end  


  
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def show
    month_str = params[:month]
    month_date = Date.strptime(month_str, '%Y-%m')
    @month = month_date.month
    @year = month_date.year
    user_id = current_user.id 
    attencance = Attendance.find_by(user_id: user_id)
    @attendance = attencance
    @attendances = Attendance.where(user_id: user_id)  
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already, except: :destroy
  def new
  end

  def create 
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to new_attendance_path, notice: "ログインに成功したよ"
    else 
      flash.now[:alert] = "メールかパスワードが違いますよ"
      ## new画面に戻る。
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have successfully logged out."
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already, only: [:new, :create]
  before_action :login, only: :show

  def new
  @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save 
      session[:user_id] = user.id
      ## noticeは処理が成功した時に出すアラート　ちなみに失敗はaler
      redirect_to new_attendance_path, notice: "新規会員登録完了"
      ## アクションを介すのがredirect_to
    else 
      ## アクションを介さないのがrender
      render :new
    end
  end

   def show
    user_id = current_user.id
    @user = User.where(id: user_id).first
    attendances = Attendance.where(user_id: user_id)  
    @attendance = attendances.last
  end

  private
  def user_params
    ## :userにparamsが入ってくる。ストロングパラメータをチェックする
    params.require(:user).permit(:name,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/new.html.erb
<div class="pt-5">
  <div>
    <h1 class="text-center">出退勤記録画面</h1>
    <h2 class="text-center"><span id="dateText"></span></h2>
    <h3 class="text-center">ようこそ "<strong><%= current_user.name %></strong>" さん</h3>
  </div>

  <div class="text-center m-3">
   <h4>
      <%= @user.decorate.work_status_alert_title %>
   </h4>
  </div>
 

    <div class="container w-50">
    <div class="row text-center">
    <div class="col">
    <%= button_to "出社", attendances_path, method: :post, class: "btn btn-outline-secondary m-1",disabled: @user.decorate.start_job_button_disabled %>
    </div>

    <div class="col">
    <%= button_to "休憩", @attendance, method: :patch, params: { type: "rest_start" }, class: "btn btn-outline-secondary m-1", disabled: @user.decorate.start_rest_button_disabled %>
    </div>

      <div class="col">
      <%= button_to "戻り", @attendance, method: :patch, params: { type: "rest_end" }, class: "btn btn-outline-secondary m-1",disabled: @user.decorate.end_rest_button_disabled %>
      </div>

      <div class="col">
      <%= button_to "退社", @attendance, method: :patch, params: { type: "end" }, class: "btn btn-outline-info m-1", disabled: @user.decorate.end_job_button_disabled %>
      </div>

      <div class="col-2">
    <%= button_to "ログアウト", logout_path, method: :delete ,class: "btn btn-primary mt-1"%>
      </div>
      </div>
    </div>

  


  

  <div class="mt-3 text-center"> 勤務表確認 </div>

<div class="w-50 mx-auto text-center">
<%= form_tag(calendar_path, method: :get) do%>
  <input type="month" name="month" class="text-center m-2" value="2022-08" required></input>
  <input type="submit" value="確認"> 
<% end %>
</div>


</div>

<script>
window.onload = function() {
  document.getElementById("dateText").innerHTML = showTime();
}
  
  function showTime() {
    const now = new Date();
    let nowMonth = now.getMonth();
    const nowDate = now.getDate();
    const nowhour = now.getHours();
    const nowminutes = now.getMinutes();
    const nowseconds = now.getSeconds();
    nowMonth += 1;

    const text = nowMonth + "月" + nowDate + "日" + nowhour + "時" + nowminutes + "分";
    return text;
  }

  let date = document.querySelector(`input[type='month'][name='month']`);
date.addEventListener(`change`, () => {
    console.log(date.value);
    document.getElementById("monthText").innerHTML = date.value;
  });
</script>

app/views/calendars/month.html.erb
<h1>Calendar</h1>

app/views/calendars/show.html.erb
<div class="m-5">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">出社時刻</th>
          <th scope="col">退社時刻</th>
          <th scope="col">休憩時間</th>
          <th scope="col">労働時間</th>
        </tr>
      </thead>
       <% @attendances.each do |attendance| %>
        <% if attendance.start_time.year.to_i == @year && attendance.start_time.month.to_i == @month %>
      <tbody>
        <tr>
          <td><%= (attendance.start_time.year).to_s + "年" + (attendance.start_time.month).to_s + "月" + (attendance.start_time.day).to_s + "日" + (attendance.start_time.hour).to_s + "時" + (attendance.start_time.min).to_s + "分" + (attendance.start_time.sec).to_s + "秒" %></td>

          <% if !attendance.end_time.nil? %>
          <td><%= (attendance.end_time.year).to_s + "年" + (attendance.end_time.month).to_s + "月" + (attendance.end_time.day).to_s + "日" + (attendance.end_time.hour).to_s + "時" + (attendance.end_time.min).to_s + "分"+ (attendance.end_time.sec).to_s + "秒"  %> </td>
           <% end %>

          <% if !attendance.rest_start_time.nil? && !attendance.rest_end_time.nil?  %>
          <td><%= ((attendance.rest_end_time.to_time - attendance.rest_start_time.to_time) / 60).floor(1).to_s + "分" %></td>
          <% end %>

          <% if !attendance.end_time.nil? && !attendance.start_time.nil? &&  !attendance.rest_start_time.nil? && !attendance.rest_end_time.nil? %>
          <td><%= (((attendance.end_time.to_time - attendance.start_time.to_time) - (attendance.rest_end_time.to_time - attendance.rest_start_time.to_time)) / 60).floor(2).to_s + "分" 
          %></td>
           <% end %>
 
        </tr>
      </tbody>
      <% end %>
      <% end %>
    </table>
  </div>
  </div>
    <div class="text-center">
    <%= link_to "もどる", new_attendance_path ,class: "btn btn-primary mt-3"%>
    </div>

app/views/homes/top.html.erb
<div class="pt-5">
<h1 class="text-center"> ホーム画面</h1>

<div>
<div class="text-center">
  <%= link_to "新規登録画面へ", new_user_path ,class: "btn btn-primary mt-3"%>
  </div>
  <div class="text-center">
  <%= link_to "ログイン画面へ", login_path ,class: "btn btn-secondary mt-3"%>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebKadai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= notice %>
  <%= alert %>
  <div class="container">
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="pt-5">
<h1 class="text-center"> 新規登録画面</h1>

<div class="w-50 mx-auto">
<%= form_with model: @user, url: user_path, local: true do |form| %>

  <div class="field form-group">
   <%= form.label :name, "名前" %>
   <%= form.text_field :name, class: "form-control", placeholder: "名前"   %>
   </div>

  <div class="field form-group">
   <%= form.label :email,"メールアドレス" %>
   <%= form.text_field :email, class: "form-control", placeholder: "メールアドレス" %>
   </div>

   <div class="field form-group">
   <%= form.label :password,"パスワード" %>
   <%= form.password_field :password, class: "form-control", placeholder: "パスワード"  %>
   </div>

   <div class="form-group">
   <%= form.submit "新規登録", class: "btn btn-primary mt-3" %>
   </div>
   <div>
  <%= link_to "ログイン画面へ", login_path ,class: "btn btn-secondary mt-3"%>
  </div>
</div>
<% end %>
</div>